name: Build and Publish Image to Docker Hub

on:
  workflow_dispatch:

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build ./api/ -t abdoul223/mon-repository:latest

      - name: Push Docker image to Docker Hub
        run: docker push abdoul223/mon-repository:latest

